apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: simple
spec:
  entrypoint: simple
  templates:
    - name: simple
      container:
        image: busybox
        command: [ echo ]
        args: [ "Hello World" ]