apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-workflow-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step1
            template: hello
        - - name: step2
            template: goodbye
        - - name: step3
            template: finish

    - name: hello
      container:
        image: busybox
        command: [ "echo" ]
        args: [ "Hello, World!" ]

    - name: goodbye
      container:
        image: busybox
        command: [ "echo" ]
        args: [ "Goodbye, World!" ]

    - name: finish
      container:
        image: busybox
        command: [ "echo" ]
        args: [ "Finish!" ]
