apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow1-
spec:
  entrypoint: runner
  templates:
    - name: runner
      steps:
        - - name: template-run
            templateRef:
              name: slack-message-template
              template: runner
            arguments:
              parameters:
                - name: message
                  value: first template-run
        - - name: template-run2
            templateRef:
              name: slack-message-template
              template: runner
            arguments:
              parameters:
                - name: message
                  value: second template-run
