apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: slack-message-template
spec:
  entrypoint: runner
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: runner
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ]